### ISSUE TITLE
HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by 89z** [uriyyo/instapi#131]
Using this program:

~~~py
from instapi import bind
bind('srpen6', 'PASSWORD')
~~~

I get this result:

~~~
Traceback (most recent call last):
  File "C:\python\lib\site-packages\instagram_private_api\client.py", line 523, in _call_api
    response = self.opener.open(req, timeout=self.timeout)
  File "urllib\request.py", line 523, in open
  File "urllib\request.py", line 632, in http_response
  File "urllib\request.py", line 561, in error
  File "urllib\request.py", line 494, in _call_chain
  File "urllib\request.py", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python\lib\site-packages\instapi\client.py", line 46, in bind
    client.obj = Client(username, password, cookie=cache.get_from_cache((username, password)))
  File "C:\python\lib\site-packages\instagram_private_api\client.py", line 208, in __init__
    self.login()
  File "C:\python\lib\site-packages\instagram_private_api\endpoints\accounts.py", line 49, in login
    login_response = self._call_api(
  File "C:\python\lib\site-packages\instapi\client_api\base.py", line 18, in _call_api
    value = super()._call_api(
  File "C:\python\lib\site-packages\instagram_private_api\client.py", line 527, in _call_api
    ErrorHandler.process(e, error_response)
  File "C:\python\lib\site-packages\instagram_private_api\errors.py", line 135, in process
    raise ClientError(error_msg, http_error.code, error_response)
instagram_private_api.errors.ClientError: Bad Request: rate_limit_error
~~~

**Comment by uriyyo** [comment]
Instagram has limitations for the amount of requests per user. You should wait for an hour and try to make request again.

**Comment by 89z** [comment]
I have waited 8 hours...
